### ISSUE TITLE
License

### ISSUE THREAD

**Issue by luto** [neoben/smart-fancy-latex-cv#5]
Thanks for providing this template! I cannot find a license statement anywhere, so this defaults to full-copyright preventing anyone from using it (legally). Can you please add a license to the README or LaTeX source? e.g. [CC-BY](https://creativecommons.org/licenses/by/2.0/).

Thank you! :)

**Comment by neoben** [comment]
LICENSE added!
Thanks for the request, I forgot to add the LICENSE when I created the repo time ago.
Cheers!

**Comment by luto** [comment]
thanks! :tada:
