### ISSUE TITLE
expl3.sty missing

### ISSUE THREAD

**Issue by alijacob** [neoben/smart-fancy-latex-cv#6]
I am compiling this LaTeX template in Windows MikTeX xelatex compiler, but log says -"expl3.sty" missing, and there's no same provided in the repository

**Comment by alijacob** [comment]
Sorry, misunderstood on this part, this issue was not solely the **LaTeX template**  issue, actually, the issue originate from `l3kernel` package, which was installed from offlline folder, it was uninstalled from MikTeX console, again installed from online live server, the issue resolved.
This issue was opened by mistake, although in my part, it was mere misunderstanding.

**Comment by neoben** [comment]
Got it!
